CREATE TABLE IF NOT EXISTS trabalho_final.USUARIO (
ID INT AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO trabalho_final.USUARIO (EMAIL, SENHA) VALUES ('admin@admin.com', '123456');